// Code generated by generator; DO NOT EDIT.

package crossplane

import (
	"reflect"
)

// nginx matchFns
var ngxOssMatchFuns = map[uintptr]interface{}{
	reflect.ValueOf(MatchOss124).Pointer(): nil,
	reflect.ValueOf(MatchOss126).Pointer(): nil,
	reflect.ValueOf(MatchOsslatest).Pointer(): nil,
}
